<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container80NkRqN\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container80NkRqN/srcProdProjectContainer.php') {
    touch(__DIR__.'/Container80NkRqN.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\Container80NkRqN\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \Container80NkRqN\srcProdProjectContainer(array(
    'container.build_hash' => '80NkRqN',
    'container.build_id' => '250cf2de',
    'container.build_time' => 1539029272,
), __DIR__.\DIRECTORY_SEPARATOR.'Container80NkRqN');
