<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.graphql.schema_builder' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Type/SchemaBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Type/SchemaBuilder.php';

return $this->privates['api_platform.graphql.schema_builder'] = new \ApiPlatform\Core\GraphQl\Type\SchemaBuilder(($this->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService()), ($this->privates['api_platform.metadata.property.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Property_MetadataFactory_CachedService()), ($this->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService()), ($this->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($this->privates['api_platform.graphql.resolver.factory.collection'] ?? $this->load('getApiPlatform_Graphql_Resolver_Factory_CollectionService.php')), ($this->privates['api_platform.graphql.resolver.factory.item_mutation'] ?? $this->load('getApiPlatform_Graphql_Resolver_Factory_ItemMutationService.php')), ($this->privates['api_platform.graphql.resolver.item'] ?? $this->load('getApiPlatform_Graphql_Resolver_ItemService.php')), ($this->privates['api_platform.graphql.resolver.resource_field'] ?? $this->load('getApiPlatform_Graphql_Resolver_ResourceFieldService.php')), ($this->privates['api_platform.filter_locator'] ?? $this->getApiPlatform_FilterLocatorService()), true);
