<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.graphql.resolver.resource_field' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/ResourceFieldResolver.php';

return $this->privates['api_platform.graphql.resolver.resource_field'] = new \ApiPlatform\Core\GraphQl\Resolver\ResourceFieldResolver(($this->privates['api_platform.iri_converter'] ?? $this->getApiPlatform_IriConverterService()));
