<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.graphql.executor' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/ExecutorInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Executor.php';

return $this->privates['api_platform.graphql.executor'] = new \ApiPlatform\Core\GraphQl\Executor();
