<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'api_platform.graphql.action.entrypoint' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/ExecutorInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Executor.php';

return $this->services['api_platform.graphql.action.entrypoint'] = new \ApiPlatform\Core\GraphQl\Action\EntrypointAction(($this->privates['api_platform.graphql.schema_builder'] ?? $this->load('getApiPlatform_Graphql_SchemaBuilderService.php')), ($this->privates['api_platform.graphql.executor'] ?? $this->privates['api_platform.graphql.executor'] = new \ApiPlatform\Core\GraphQl\Executor()), ($this->services['twig'] ?? $this->getTwigService()), true, false, '');
