<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.graphql.resolver.factory.collection' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/ResolverFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/FieldsToAttributesTrait.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/ResourceAccessCheckerTrait.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/CollectionResolverFactory.php';

return $this->privates['api_platform.graphql.resolver.factory.collection'] = new \ApiPlatform\Core\GraphQl\Resolver\Factory\CollectionResolverFactory(($this->privates['api_platform.collection_data_provider'] ?? $this->getApiPlatform_CollectionDataProviderService()), ($this->privates['api_platform.subresource_data_provider'] ?? $this->getApiPlatform_SubresourceDataProviderService()), ($this->services['serializer'] ?? $this->getSerializerService()), ($this->privates['api_platform.identifiers_extractor.cached'] ?? $this->getApiPlatform_IdentifiersExtractor_CachedService()), ($this->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($this->privates['api_platform.security.resource_access_checker'] ?? $this->getApiPlatform_Security_ResourceAccessCheckerService()), ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()), true);
