<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.graphql.resolver.factory.item_mutation' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/ResolverFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/FieldsToAttributesTrait.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/ResourceAccessCheckerTrait.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php';

return $this->privates['api_platform.graphql.resolver.factory.item_mutation'] = new \ApiPlatform\Core\GraphQl\Resolver\Factory\ItemMutationResolverFactory(($this->privates['api_platform.iri_converter'] ?? $this->getApiPlatform_IriConverterService()), ($this->privates['api_platform.data_persister'] ?? $this->load('getApiPlatform_DataPersisterService.php')), ($this->services['serializer'] ?? $this->getSerializerService()), ($this->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), ($this->privates['api_platform.security.resource_access_checker'] ?? $this->getApiPlatform_Security_ResourceAccessCheckerService()), ($this->privates['api_platform.validator'] ?? $this->load('getApiPlatform_ValidatorService.php')));
