<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPclxjy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPclxjy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXPclxjy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXPclxjy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXPclxjy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XPclxjy',
    'container.build_id' => '704dcba5',
    'container.build_time' => 1561047891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPclxjy');
