<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLOP5A9L\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLOP5A9L/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLOP5A9L.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLOP5A9L\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLOP5A9L\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LOP5A9L',
    'container.build_id' => '8d1b7cdc',
    'container.build_time' => 1561042604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLOP5A9L');
