<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH0jMnur\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH0jMnur/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH0jMnur.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH0jMnur\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerH0jMnur\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'H0jMnur',
    'container.build_id' => '310a5c0c',
    'container.build_time' => 1539029284,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerH0jMnur');
