<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/OrderedFixtureInterface.php';
include_once $this->targetDirs[3].'/src/DataFixtures/Traits/TimestampableTrait.php';
include_once $this->targetDirs[3].'/src/DataFixtures/Traits/AccessorTrait.php';
include_once $this->targetDirs[3].'/src/DataFixtures/AssignmentFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/CropFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/CustomerFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/FarmFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/GreenhouseFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/HarvestFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/OrderFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/OrderItemFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/PhaseFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/PollinateFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/PostFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ProgressionFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/SheetFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/SowingFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/TransplantFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/UnitFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/UserFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/VarietyFixtures.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([0 => ['fixture' => new \App\DataFixtures\AssignmentFixtures(), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\CropFixtures(), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\CustomerFixtures(), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\FarmFixtures(), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\GreenhouseFixtures(), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\HarvestFixtures(), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\OrderFixtures(), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\OrderItemFixtures(), 'groups' => []], 8 => ['fixture' => new \App\DataFixtures\PhaseFixtures(), 'groups' => []], 9 => ['fixture' => new \App\DataFixtures\PollinateFixtures(), 'groups' => []], 10 => ['fixture' => new \App\DataFixtures\PostFixtures(), 'groups' => []], 11 => ['fixture' => new \App\DataFixtures\ProgressionFixtures(), 'groups' => []], 12 => ['fixture' => new \App\DataFixtures\SheetFixtures(), 'groups' => []], 13 => ['fixture' => new \App\DataFixtures\SowingFixtures(), 'groups' => []], 14 => ['fixture' => new \App\DataFixtures\TransplantFixtures(), 'groups' => []], 15 => ['fixture' => new \App\DataFixtures\UnitFixtures(), 'groups' => []], 16 => ['fixture' => new \App\DataFixtures\UserFixtures(($this->services['security.password_encoder'] ?? $this->getSecurity_PasswordEncoderService())), 'groups' => []], 17 => ['fixture' => new \App\DataFixtures\VarietyFixtures(), 'groups' => []]]);

$this->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($this->services['doctrine'] ?? $this->getDoctrineService()));

$instance->setName('doctrine:fixtures:load');

return $instance;
