<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Option extends Model {
	//
	/**
	 * The products that belong to the role.
	 */
	public function products() {
		return $this->belongsToMany(Product::class, 'product_option');
	}

	public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        return [
            'content'=>$data['content'],
            'description'=>$data['description'],
            'id'=>$data['id'],
            'is_default'=>$data['is_default'],
            'max_quantity'=>$data['max_quantity'],
            'price'=>$data['price'],
            'title'=>$data['title'],
            'top_order'=>$data['top_order'],
            'weight'=> $data['weight']
        ];
    }
}
