<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\Pivot;
class ProductOption extends Pivot {

    protected $table = 'product_option';
	protected $fillable = [
		'title', 'slug', 'min_select', 'max_select',
	];

	public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        return [
            'title' => $data['title'],
            'max_select' => $data['max_select'],
            'min_select' => $data['min_select'],
        ];
    }
}
