<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/OrderedFixtureInterface.php';
include_once $this->targetDirs[3].'/src/DataFixtures/Traits/TimestampableTrait.php';
include_once $this->targetDirs[3].'/src/DataFixtures/Traits/AccessorTrait.php';
include_once $this->targetDirs[3].'/src/DataFixtures/AssignmentFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/CropFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/CustomerFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/FarmFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/GreenhouseFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/HarvestFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/OrderFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/OrderItemFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/PhaseFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/PollinateFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ProgressionFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/SheetFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/SowingFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/TransplantFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/UnitFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/UserFixtures.php';
include_once $this->targetDirs[3].'/src/DataFixtures/VarietyFixtures.php';
include_once $this->targetDirs[3].'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once $this->targetDirs[3].'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures(array(0 => new \App\DataFixtures\AssignmentFixtures(), 1 => new \App\DataFixtures\CropFixtures(), 2 => new \App\DataFixtures\CustomerFixtures(), 3 => new \App\DataFixtures\FarmFixtures(), 4 => new \App\DataFixtures\GreenhouseFixtures(), 5 => new \App\DataFixtures\HarvestFixtures(), 6 => new \App\DataFixtures\OrderFixtures(), 7 => new \App\DataFixtures\OrderItemFixtures(), 8 => new \App\DataFixtures\PhaseFixtures(), 9 => new \App\DataFixtures\PollinateFixtures(), 10 => new \App\DataFixtures\ProgressionFixtures(), 11 => new \App\DataFixtures\SheetFixtures(), 12 => new \App\DataFixtures\SowingFixtures(), 13 => new \App\DataFixtures\TransplantFixtures(), 14 => new \App\DataFixtures\UnitFixtures(), 15 => new \App\DataFixtures\UserFixtures(($this->services['security.password_encoder'] ?? $this->getSecurity_PasswordEncoderService())), 16 => new \App\DataFixtures\VarietyFixtures()));

$this->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a);

$instance->setName('doctrine:fixtures:load');

return $instance;
