<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOL2POBC\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOL2POBC/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOL2POBC.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOL2POBC\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerOL2POBC\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'OL2POBC',
    'container.build_id' => '748e5f93',
    'container.build_time' => 1539063529,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOL2POBC');
